# This workflow will install Python dependencies and run the linter
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    name: Lint with ruff
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Set up Python 3.11
      uses: actions/setup-python@v7
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |  
        python -m pip install --upgrade pip
        python -m pip install --editable .[lint]

    - name: Run linter check
      run: |
        python -m ruff check --output-format=github src/ tests/

    - name: Run linter format
      run: |
        python -m ruff format --check src/ tests/
